In [1]:
import sys
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objs as go
from plotly.subplots import make_subplots
import plotly.io as pio
pio.renderers.default = 'colab'

/home/tatiana/Programas/anaconda3/envs/bioconda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)

In [2]:
# Import local seqDataClass package
sys.path.append("/home/tatiana/Programas/seqDataClass/")
from seqDataClass import seqObject

In [3]:
# 1. Define base path (ensure the trailing slash '/')
filepath = "/home/tatiana/PROYECTOS/repository/"

# Load and inspect metadata
metadata_file = filepath + "metadata.csv"
df1 = pd.read_csv(metadata_file)
print("Metadata preview:")
display(df1.head())

Metadata preview:

,sample_name,copy,location,average,date,height,area,depth,coordinate,Chlorophyll,...,Fluoride,Chloride,Nitrate,Sulphate,recount_MM,recount_DG18,recount_SNA,recount_R2A,recount_RB,recount_MY10-12
0,its-LC1,1,LC,1,4_10_2023,3050,21000,2.1,37.05957_-3.33433,1.77,...,25,876,475.0,1713,1,1,0,2,0,0
1,its-LC2,2,LC,1,4_10_2023,3050,21000,2.1,37.05957_-3.33434,1.77,...,25,876,475.0,1713,1,1,0,2,0,0
2,its-LC3,3,LC,1,4_10_2023,3050,21000,2.1,37.05957_-3.33435,1.77,...,25,876,475.0,1713,1,1,0,2,0,0
3,its-LL1,1,LL,2,11_09_2023,2870,17700,U,37.05957_-3.33433,1.30,...,35,929,442.0,3774,0,2,2,3,0,0
4,its-LL2,2,LL,2,11_09_2023,2870,17700,U,37.05957_-3.33434,1.30,...,35,929,442.0,3774,0,2,2,3,0,0

In [4]:
# temporary pathc OOOOOO # # Inspect and ensure the primary identifier column is explicitly named 'feature-id'
filepath = "/home/tatiana/PROYECTOS/repository/"
tax_path = filepath + "taxonomy.csv"
df_tax = pd.read_csv(tax_path)
if 'feature-id' not in df_tax.columns:
    if 'Sequence' in df_tax.columns:
        df_tax.rename(columns={'Sequence': 'feature-id'}, inplace=True)
    else:
        df_tax.columns.values[0] = 'feature-id'
    df_tax.to_csv(tax_path, index=False)

In [5]:
# Initialize seqObject
seqOne = seqObject(
    mappingFile = filepath + "metadata.csv",
    taxonomyFile = tax_path,
    featureFile = filepath + "feature_table.csv",
    mappingSep = ",",
    taxonomySep = ",",
    featureSep = ",",
    sampleNamesColumn = "sample_name",
    featureFormat = "dada2",
    taxonomyFormat = "seqDataClass"
)

Initializing data loading.
Loading mapping file
Loading taxonomy
Taxonomy has some redundant features. Attempting to prune these.
Matching features between feature file and taxonomy file.
Features match.

In [6]:
# Check the dimensions to check number of samples
print("Abundance matrix size", seqOne.data.shape)

Abundance matrix size (1023, 9)

In [7]:
seqOne.data

,,,,,,,,sample_name,its-LC1,its-LC2,its-LC3,its-LL1,its-LL2,its-LL3,its-LRS1,its-LRS2,its-LRS3
,,,,,,,,copy,1,2,3,1,2,3,1,2,3
,,,,,,,,location,LC,LC,LC,LL,LL,LL,LRS,LRS,LRS
,,,,,,,,average,1,1,1,2,2,2,3,3,3
,,,,,,,,date,4_10_2023,4_10_2023,4_10_2023,11_09_2023,11_09_2023,11_09_2023,4_10_2023,4_10_2023,4_10_2023
,,,,,,,,height,3050,3050,3050,2870,2870,2870,2987,2987,2987
,,,,,,,,area,21000,21000,21000,17700,17700,17700,4200,4200,4200
,,,,,,,,depth,2.1,2.1,2.1,U,U,U,1.6,1.6,1.6
,,,,,,,,coordinate,37.05957_-3.33433,37.05957_-3.33434,37.05957_-3.33435,37.05957_-3.33433,37.05957_-3.33434,37.05957_-3.33435,37.052113_-3.345583,37.052113_-3.345584,37.052113_-3.345585
,,,,,,,,Chlorophyll,1.77,1.77,1.77,1.30,1.30,1.30,0.84,0.84,0.84
,,,,,,,,Conductivity,54.25,54.25,54.25,76.29,76.29,76.29,58.02,58.02,58.02
,,,,,,,,fDOM,4.03,4.03,4.03,1.89,1.89,1.89,3.88,3.88,3.88
,,,,,,,,ORP,267.45,267.45,267.45,311.74,311.74,311.74,278.49,278.49,278.49
,,,,,,,,Salinity,0.03,0.03,0.03,0.05,0.05,0.05,0.03,0.03,0.03
,,,,,,,,TDS,47.00,47.00,47.00,72.00,72.00,72.00,37.09,37.09,37.09
,,,,,,,,pH,8.23,8.23,8.23,7.18,7.18,7.18,8.42,8.42,8.42
,,,,,,,,Temperature,11.58,11.58,11.58,8.52,8.52,8.52,11.78,11.78,11.78
,,,,,,,,Oxigen_1,103.13,103.13,103.13,105.42,105.42,105.42,101.43,101.43,101.43
,,,,,,,,Oxigen_2,12.04,12.04,12.04,13.78,13.78,13.78,12.35,12.35,12.35
,,,,,,,,Alkalinity,0.83,0.83,0.83,0.95,0.95,0.95,0.70,0.70,0.70
,,,,,,,,TAC,4.21,4.21,4.21,4.76,4.76,4.76,3.70,3.70,3.70
,,,,,,,,filtered_volume,11.0,11.0,11.0,11.0,11.0,11.0,5.5,5.5,5.5
,,,,,,,,max_depth,2.1,2.1,2.1,5.0,5.0,5.0,1.8,1.8,1.8
,,,,,,,,sechi_depth,2.1,2.1,2.1,5.0,5.0,5.0,1.8,1.8,1.8
,,,,,,,,Sodium,3,3,3,4,4,4,6,6,6
,,,,,,,,Ammonium,6.00,6.00,6.00,52.00,52.00,52.00,0.05,0.05,0.05
,,,,,,,,Potassium,236,236,236,309,309,309,234,234,234
,,,,,,,,Calcium,12711,12711,12711,14947,14947,14947,10176,10176,10176
,,,,,,,,Magnesium,1222,1222,1222,1052,1052,1052,1384,1384,1384
,,,,,,,,Fluoride,25,25,25,35,35,35,66,66,66
,,,,,,,,Chloride,876,876,876,929,929,929,804,804,804
,,,,,,,,Nitrate,475.00,475.00,475.00,442.00,442.00,442.00,0.45,0.45,0.45
,,,,,,,,Sulphate,1713,1713,1713,3774,3774,3774,2252,2252,2252
,,,,,,,,recount_MM,1,1,1,0,0,0,1,1,1
,,,,,,,,recount_DG18,1,1,1,2,2,2,0,0,0
,,,,,,,,recount_SNA,0,0,0,2,2,2,0,0,0
,,,,,,,,recount_R2A,2,2,2,3,3,3,2,2,2
,,,,,,,,recount_RB,0,0,0,0,0,0,0,0,0
,,,,,,,,recount_MY10-12,0,0,0,0,0,0,1,1,1
feature-id,Kingdom,Phylum,Class,Order,Family,Genus,Species,tax_rank,,,,,,,,,
TCGAGTTTACAACTCCCAAAACCCCTGTGAACATACCTATCGTTGCTTCGGCGGGATCGCCCCGGCGCCTCCGGGCCCGGACCCAGGCGCCCGCCGGAGGACCCAAACTCTTGAATTTACGGTGTATCTTCTGAGTGAAACAAGCAAATAAATCA,k__Fungi,p__Ascomycota,c__Sordariomycetes,o__Hypocreales,f__Nectriaceae,g__Paracremonium,NaN,0.0,0,325,147,18,35607,11816,0,0,350477
CCGAGTTTACAACTCCCAAACCCCTGTGAACATACCTATCGTTGCTTCGGCGGAGTCGTCCCGGCGTCCCCCTCTCCGGAGGAGGGCCCGGACCCAGGCGCCCGCCGGAGGACCCAAACTCCTGTTTCATTTTGAGTATCTTCTGAGTAAAACAAGCAAATAAATCA,k__Fungi,p__Ascomycota,c__Sordariomycetes,o__Hypocreales,f__Nectriaceae,g__Cosmospora,NaN,1.0,0,87,439,0,26516,5610,0,889,283748
ACAAATCCTGCTGCAGTACCGCAAGGTGCTGTAGTATATTAACTCGGCCTGTGTCGCAAGATGCAGGCTGACTATATAAATGTGTGTAATGTAGACAATGTGTGTGTGATTAATTAGTAGA,k__Fungi,p__Rozellomycota,c__Rozellomycota_cls_Incertae_sedis,o__Rozellomycota_ord_Incertae_sedis,f__Rozellomycota_fam_Incertae_sedis,g__Rozellomycota_gen_Incertae_sedis,NaN,2.0,62678,152077,39725,3061,0,2755,0,0,1205
AGAGAATATTGGACTTTGGTCCATTTATCTACCCATCTACACCTGTGAACTGTTTATGTGCTTCGGCACGTTTTACACAAACTTCTAAATGTAATGAATGTAATCATATTATAACAATAATA,k__Fungi,p__Basidiomycota,c__Tremellomycetes,o__Tremellales,f__Cryptococcaceae,g__Cryptococcus,s__neoformans,3.0,0,584,8,0,309,234,0,0,0
ACAAATCTATAGGCGGCCTAGCCGTCGTTAACCAATGTGAATTGGGAGGGTTTATCTCTCTCTAGTAAACTATAACGAGTCGGATAAAAAAATTAATTGAAA,k__Fungi,NaN,NaN,NaN,NaN,NaN,NaN,4.0,30589,53145,8192,2273,0,4049,0,0,212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CACGAAACGCGTGGATGTGCGGACGTCGCAAGGCGCCCGCACTCTCACACACACACCCTTGTGAACTGTAAGCGTACACCTTTGGCACGCGAGTGCCAAACGGTACCCACCCCATTACACCTGTCAACACGTCACAACTGAAACAAACACAAAATTAAATA,k__Fungi,NaN,NaN,NaN,NaN,NaN,NaN,1018.0,0,0,0,143,0,0,0,0,0
CCAAAAAGGTCTAAGACCTATACCCCTTGTGCATTGTTTAATTGTCTTTGCGGGGTAAGGGCTTGAACGTAGGTTTATATCTGCTATCTTTCCAAGCCTCGCAAACTATGCTTAACTCCAAAAATATCTGTGATGGTGGACTAAAACAAAAACAAAAGA,k__Fungi,NaN,NaN,NaN,NaN,NaN,NaN,1019.0,0,0,0,143,0,0,0,0,0
CTGAGTTATCCAACTCCCAAACCCCTGTGAACATACCTATGTTGCTTCGGCGGACCGTCCCGCGGCGCGCCCTCGTGGCGTGACCCGGACCCAGGCGCCCGCCGGGGAACCGAAACTCTTGTCTTCCAGTGTCTCCTCTGAGTGGCATAAGCAAAAATAAATA,k__Fungi,p__Ascomycota,c__Sordariomycetes,o__Hypocreales,f__Bionectriaceae,g__Acremonium,s__tubakii,1020.0,0,0,0,93,0,50,0,0,0
CAGGACTCGCAAGGCTCCCGTAACCACTGTGAACTTACCTATATTCGTTGCCTCGGCGGGTGCCCTAGACTCATATCTAGGGCATTCAACCCGCCGGTGGCCTACAACTCTGTCTCGCGCGTTGGCATCTCCGAGTCATTTTAAACGAGTCA,k__Fungi,p__Ascomycota,c__Sordariomycetes,o__Chaetosphaeriales,f__Chaetosphaeriaceae,g__Chaetosphaeria,s__ciliata,1021.0,0,0,0,0,0,143,0,0,0
CAGTGTTCCCTGCCCTCATGGGTAGAAACGCCCACCCTTTGTGTAATATATCTTGTTGCTTTGGCGGGCCGCCTTCGGGCACCGGCTTCGGCTGGGTTGCGCCTGCCAGAGGACCCCAAACTCTGAATGTTAGTGTCGTCTGAGTACTATATAATAGTTA,k__Fungi,p__Ascomycota,c__Leotiomycetes,o__Helotiales,f__Helotiaceae,g__Glarea,NaN,1022.0,142,0,0,0,0,0,0,0,0

In [8]:
seqOne.data.columns.to_frame(index = False)

,sample_name,copy,location,average,date,height,area,depth,coordinate,Chlorophyll,...,Fluoride,Chloride,Nitrate,Sulphate,recount_MM,recount_DG18,recount_SNA,recount_R2A,recount_RB,recount_MY10-12
0,its-LC1,1,LC,1,4_10_2023,3050,21000,2.1,37.05957_-3.33433,1.77,...,25,876,475.00,1713,1,1,0,2,0,0
1,its-LC2,2,LC,1,4_10_2023,3050,21000,2.1,37.05957_-3.33434,1.77,...,25,876,475.00,1713,1,1,0,2,0,0
2,its-LC3,3,LC,1,4_10_2023,3050,21000,2.1,37.05957_-3.33435,1.77,...,25,876,475.00,1713,1,1,0,2,0,0
3,its-LL1,1,LL,2,11_09_2023,2870,17700,U,37.05957_-3.33433,1.30,...,35,929,442.00,3774,0,2,2,3,0,0
4,its-LL2,2,LL,2,11_09_2023,2870,17700,U,37.05957_-3.33434,1.30,...,35,929,442.00,3774,0,2,2,3,0,0
5,its-LL3,3,LL,2,11_09_2023,2870,17700,U,37.05957_-3.33435,1.30,...,35,929,442.00,3774,0,2,2,3,0,0
6,its-LRS1,1,LRS,3,4_10_2023,2987,4200,1.6,37.052113_-3.345583,0.84,...,66,804,0.45,2252,1,0,0,2,0,1
7,its-LRS2,2,LRS,3,4_10_2023,2987,4200,1.6,37.052113_-3.345584,0.84,...,66,804,0.45,2252,1,0,0,2,0,1
8,its-LRS3,3,LRS,3,4_10_2023,2987,4200,1.6,37.052113_-3.345585,0.84,...,66,804,0.45,2252,1,0,0,2,0,1

In [9]:
seqOne.data.index.to_frame(index = False)

,feature-id,Kingdom,Phylum,Class,Order,Family,Genus,Species,tax_rank
0,TCGAGTTTACAACTCCCAAAACCCCTGTGAACATACCTATCGTTGC...,k__Fungi,p__Ascomycota,c__Sordariomycetes,o__Hypocreales,f__Nectriaceae,g__Paracremonium,NaN,0.0
1,CCGAGTTTACAACTCCCAAACCCCTGTGAACATACCTATCGTTGCT...,k__Fungi,p__Ascomycota,c__Sordariomycetes,o__Hypocreales,f__Nectriaceae,g__Cosmospora,NaN,1.0
2,ACAAATCCTGCTGCAGTACCGCAAGGTGCTGTAGTATATTAACTCG...,k__Fungi,p__Rozellomycota,c__Rozellomycota_cls_Incertae_sedis,o__Rozellomycota_ord_Incertae_sedis,f__Rozellomycota_fam_Incertae_sedis,g__Rozellomycota_gen_Incertae_sedis,NaN,2.0
3,AGAGAATATTGGACTTTGGTCCATTTATCTACCCATCTACACCTGT...,k__Fungi,p__Basidiomycota,c__Tremellomycetes,o__Tremellales,f__Cryptococcaceae,g__Cryptococcus,s__neoformans,3.0
4,ACAAATCTATAGGCGGCCTAGCCGTCGTTAACCAATGTGAATTGGG...,k__Fungi,NaN,NaN,NaN,NaN,NaN,NaN,4.0
...,...,...,...,...,...,...,...,...,...
1018,CACGAAACGCGTGGATGTGCGGACGTCGCAAGGCGCCCGCACTCTC...,k__Fungi,NaN,NaN,NaN,NaN,NaN,NaN,1018.0
1019,CCAAAAAGGTCTAAGACCTATACCCCTTGTGCATTGTTTAATTGTC...,k__Fungi,NaN,NaN,NaN,NaN,NaN,NaN,1019.0
1020,CTGAGTTATCCAACTCCCAAACCCCTGTGAACATACCTATGTTGCT...,k__Fungi,p__Ascomycota,c__Sordariomycetes,o__Hypocreales,f__Bionectriaceae,g__Acremonium,s__tubakii,1020.0
1021,CAGGACTCGCAAGGCTCCCGTAACCACTGTGAACTTACCTATATTC...,k__Fungi,p__Ascomycota,c__Sordariomycetes,o__Chaetosphaeriales,f__Chaetosphaeriaceae,g__Chaetosphaeria,s__ciliata,1021.0
1022,CAGTGTTCCCTGCCCTCATGGGTAGAAACGCCCACCCTTTGTGTAA...,k__Fungi,p__Ascomycota,c__Leotiomycetes,o__Helotiales,f__Helotiaceae,g__Glarea,NaN,1022.0

In [10]:
seqSamp = seqOne.data.sum()
type(seqSamp)

pandas.core.series.Series

In [11]:
sampleNames = seqSamp.index.to_frame(index = False) ["sample_name"] 
sampleNames

0     its-LC1
1     its-LC2
2     its-LC3
3     its-LL1
4     its-LL2
5     its-LL3
6    its-LRS1
7    its-LRS2
8    its-LRS3
Name: sample_name, dtype: object

In [12]:
seqSamp.index = sampleNames
seqSamp

sample_name
its-LC1     294938
its-LC2     594035
its-LC3     193840
its-LL1     243902
its-LL2     156488
its-LL3     281367
its-LRS1     43515
its-LRS2    129207
its-LRS3    813902
dtype: int64

In [13]:
seqSamp.to_frame()

                  0
sample_name
its-LC1      294938
its-LC2      594035
its-LC3      193840
its-LL1      243902
its-LL2      156488
its-LL3      281367
its-LRS1      43515
its-LRS2     129207
its-LRS3     813902

In [14]:
fig1 = go.Figure([go.Bar(x = seqSamp.index, y = seqSamp)])
fig1

In [15]:
fig1

fig1.write_image("ASVs_fig_rarefaction.pdf")

In [16]:
fig1

fig1.write_image("ASVs_fig_rarefaction.pdf")

In [17]:
# Rarefaction will be determined by the samles with the lowest number of readsyo he selecciondao its-LRS1 como punto de partida porque si cogo el de LL2, perderíamos un monton de secuencias.

seqOne.rarefy_to_even_depth(seqDepth = 43515, seed = 48) ## cambiar el rarefaction según el grupo de muestras

Removing 4 features/OTUs that no longer appear in any sample.

In [18]:
# If seqOne.data is already a pandas DataFrame

seqOne_data = seqOne.data 


# Export DataFrame to CSV

seqOne_data.to_csv('ASVs_seqOne_data.csv', index=False)

In [19]:
# Plots
fig = seqOne.stacked_barplot(tax_level = "Order", map_level = ["copy", "location"])

fig

end

/home/tatiana/Programas/seqDataClass/seqDataClass.py:1017: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [20]:
fig1 = seqOne.stacked_barplot(tax_level = "Genus", map_level = ["location", "average"])

# not sure if that will be average or sum?

fig1

end

In [21]:
fig1.write_image("fig-asvs_abundance_genus.pdf")

In [22]:
print("1. Type:", type(seqOne.data))
print("2. Shape/Length:", getattr(seqOne.data, "shape", len(seqOne.data)))
print("3. First elements or head:")
display(seqOne.data) if hasattr(seqOne.data, "head") else print(seqOne.data[:2])

1. Type: <class 'pandas.core.frame.DataFrame'>
2. Shape/Length: (1019, 9)
3. First elements or head:

,,,,,,,,sample_name,its-LC1,its-LC2,its-LC3,its-LL1,its-LL2,its-LL3,its-LRS1,its-LRS2,its-LRS3
,,,,,,,,copy,1,2,3,1,2,3,1,2,3
,,,,,,,,location,LC,LC,LC,LL,LL,LL,LRS,LRS,LRS
,,,,,,,,average,1,1,1,2,2,2,3,3,3
,,,,,,,,date,4_10_2023,4_10_2023,4_10_2023,11_09_2023,11_09_2023,11_09_2023,4_10_2023,4_10_2023,4_10_2023
,,,,,,,,height,3050,3050,3050,2870,2870,2870,2987,2987,2987
,,,,,,,,area,21000,21000,21000,17700,17700,17700,4200,4200,4200
,,,,,,,,depth,2.1,2.1,2.1,U,U,U,1.6,1.6,1.6
,,,,,,,,coordinate,37.05957_-3.33433,37.05957_-3.33434,37.05957_-3.33435,37.05957_-3.33433,37.05957_-3.33434,37.05957_-3.33435,37.052113_-3.345583,37.052113_-3.345584,37.052113_-3.345585
,,,,,,,,Chlorophyll,1.77,1.77,1.77,1.30,1.30,1.30,0.84,0.84,0.84
,,,,,,,,Conductivity,54.25,54.25,54.25,76.29,76.29,76.29,58.02,58.02,58.02
,,,,,,,,fDOM,4.03,4.03,4.03,1.89,1.89,1.89,3.88,3.88,3.88
,,,,,,,,ORP,267.45,267.45,267.45,311.74,311.74,311.74,278.49,278.49,278.49
,,,,,,,,Salinity,0.03,0.03,0.03,0.05,0.05,0.05,0.03,0.03,0.03
,,,,,,,,TDS,47.00,47.00,47.00,72.00,72.00,72.00,37.09,37.09,37.09
,,,,,,,,pH,8.23,8.23,8.23,7.18,7.18,7.18,8.42,8.42,8.42
,,,,,,,,Temperature,11.58,11.58,11.58,8.52,8.52,8.52,11.78,11.78,11.78
,,,,,,,,Oxigen_1,103.13,103.13,103.13,105.42,105.42,105.42,101.43,101.43,101.43
,,,,,,,,Oxigen_2,12.04,12.04,12.04,13.78,13.78,13.78,12.35,12.35,12.35
,,,,,,,,Alkalinity,0.83,0.83,0.83,0.95,0.95,0.95,0.70,0.70,0.70
,,,,,,,,TAC,4.21,4.21,4.21,4.76,4.76,4.76,3.70,3.70,3.70
,,,,,,,,filtered_volume,11.0,11.0,11.0,11.0,11.0,11.0,5.5,5.5,5.5
,,,,,,,,max_depth,2.1,2.1,2.1,5.0,5.0,5.0,1.8,1.8,1.8
,,,,,,,,sechi_depth,2.1,2.1,2.1,5.0,5.0,5.0,1.8,1.8,1.8
,,,,,,,,Sodium,3,3,3,4,4,4,6,6,6
,,,,,,,,Ammonium,6.00,6.00,6.00,52.00,52.00,52.00,0.05,0.05,0.05
,,,,,,,,Potassium,236,236,236,309,309,309,234,234,234
,,,,,,,,Calcium,12711,12711,12711,14947,14947,14947,10176,10176,10176
,,,,,,,,Magnesium,1222,1222,1222,1052,1052,1052,1384,1384,1384
,,,,,,,,Fluoride,25,25,25,35,35,35,66,66,66
,,,,,,,,Chloride,876,876,876,929,929,929,804,804,804
,,,,,,,,Nitrate,475.00,475.00,475.00,442.00,442.00,442.00,0.45,0.45,0.45
,,,,,,,,Sulphate,1713,1713,1713,3774,3774,3774,2252,2252,2252
,,,,,,,,recount_MM,1,1,1,0,0,0,1,1,1
,,,,,,,,recount_DG18,1,1,1,2,2,2,0,0,0
,,,,,,,,recount_SNA,0,0,0,2,2,2,0,0,0
,,,,,,,,recount_R2A,2,2,2,3,3,3,2,2,2
,,,,,,,,recount_RB,0,0,0,0,0,0,0,0,0
,,,,,,,,recount_MY10-12,0,0,0,0,0,0,1,1,1
feature-id,Kingdom,Phylum,Class,Order,Family,Genus,Species,tax_rank,,,,,,,,,
TCGAGTTTACAACTCCCAAAACCCCTGTGAACATACCTATCGTTGCTTCGGCGGGATCGCCCCGGCGCCTCCGGGCCCGGACCCAGGCGCCCGCCGGAGGACCCAAACTCTTGAATTTACGGTGTATCTTCTGAGTGAAACAAGCAAATAAATCA,k__Fungi,p__Ascomycota,c__Sordariomycetes,o__Hypocreales,f__Nectriaceae,g__Paracremonium,NaN,0.0,0,32,32,2,9857,1871,0,0,18816
CCGAGTTTACAACTCCCAAACCCCTGTGAACATACCTATCGTTGCTTCGGCGGAGTCGTCCCGGCGTCCCCCTCTCCGGAGGAGGGCCCGGACCCAGGCGCCCGCCGGAGGACCCAAACTCCTGTTTCATTTTGAGTATCTTCTGAGTAAAACAAGCAAATAAATCA,k__Fungi,p__Ascomycota,c__Sordariomycetes,o__Hypocreales,f__Nectriaceae,g__Cosmospora,NaN,1.0,0,7,89,0,7274,858,0,272,15129
ACAAATCCTGCTGCAGTACCGCAAGGTGCTGTAGTATATTAACTCGGCCTGTGTCGCAAGATGCAGGCTGACTATATAAATGTGTGTAATGTAGACAATGTGTGTGTGATTAATTAGTAGA,k__Fungi,p__Rozellomycota,c__Rozellomycota_cls_Incertae_sedis,o__Rozellomycota_ord_Incertae_sedis,f__Rozellomycota_fam_Incertae_sedis,g__Rozellomycota_gen_Incertae_sedis,NaN,2.0,9151,11089,8985,597,0,434,0,0,63
AGAGAATATTGGACTTTGGTCCATTTATCTACCCATCTACACCTGTGAACTGTTTATGTGCTTCGGCACGTTTTACACAAACTTCTAAATGTAATGAATGTAATCATATTATAACAATAATA,k__Fungi,p__Basidiomycota,c__Tremellomycetes,o__Tremellales,f__Cryptococcaceae,g__Cryptococcus,s__neoformans,3.0,0,42,1,0,100,27,0,0,0
ACAAATCTATAGGCGGCCTAGCCGTCGTTAACCAATGTGAATTGGGAGGGTTTATCTCTCTCTAGTAAACTATAACGAGTCGGATAAAAAAATTAATTGAAA,k__Fungi,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4621,3960,1868,463,0,647,0,0,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CACGAAACGCGTGGATGTGCGGACGTCGCAAGGCGCCCGCACTCTCACACACACACCCTTGTGAACTGTAAGCGTACACCTTTGGCACGCGAGTGCCAAACGGTACCCACCCCATTACACCTGTCAACACGTCACAACTGAAACAAACACAAAATTAAATA,k__Fungi,NaN,NaN,NaN,NaN,NaN,NaN,1018.0,0,0,0,20,0,0,0,0,0
CCAAAAAGGTCTAAGACCTATACCCCTTGTGCATTGTTTAATTGTCTTTGCGGGGTAAGGGCTTGAACGTAGGTTTATATCTGCTATCTTTCCAAGCCTCGCAAACTATGCTTAACTCCAAAAATATCTGTGATGGTGGACTAAAACAAAAACAAAAGA,k__Fungi,NaN,NaN,NaN,NaN,NaN,NaN,1019.0,0,0,0,28,0,0,0,0,0
CTGAGTTATCCAACTCCCAAACCCCTGTGAACATACCTATGTTGCTTCGGCGGACCGTCCCGCGGCGCGCCCTCGTGGCGTGACCCGGACCCAGGCGCCCGCCGGGGAACCGAAACTCTTGTCTTCCAGTGTCTCCTCTGAGTGGCATAAGCAAAAATAAATA,k__Fungi,p__Ascomycota,c__Sordariomycetes,o__Hypocreales,f__Bionectriaceae,g__Acremonium,s__tubakii,1020.0,0,0,0,19,0,7,0,0,0
CAGGACTCGCAAGGCTCCCGTAACCACTGTGAACTTACCTATATTCGTTGCCTCGGCGGGTGCCCTAGACTCATATCTAGGGCATTCAACCCGCCGGTGGCCTACAACTCTGTCTCGCGCGTTGGCATCTCCGAGTCATTTTAAACGAGTCA,k__Fungi,p__Ascomycota,c__Sordariomycetes,o__Chaetosphaeriales,f__Chaetosphaeriaceae,g__Chaetosphaeria,s__ciliata,1021.0,0,0,0,0,0,20,0,0,0
CAGTGTTCCCTGCCCTCATGGGTAGAAACGCCCACCCTTTGTGTAATATATCTTGTTGCTTTGGCGGGCCGCCTTCGGGCACCGGCTTCGGCTGGGTTGCGCCTGCCAGAGGACCCCAAACTCTGAATGTTAGTGTCGTCTGAGTACTATATAATAGTTA,k__Fungi,p__Ascomycota,c__Leotiomycetes,o__Helotiales,f__Helotiaceae,g__Glarea,NaN,1022.0,21,0,0,0,0,0,0,0,0

In [23]:
# Define your file paths (update names if your files differ slightly)
counts_path = filepath + "feature_table.csv"          # Or your abundance/feature table
taxonomy_path = filepath + "taxonomy.csv"          # Your taxonomy table
metadata_path = filepath + "metadata.csv"

In [24]:
# Load datasets
df_counts = pd.read_csv(counts_path, index_col=0)
df_tax = pd.read_csv(taxonomy_path, index_col=0)
metadata = pd.read_csv(metadata_path)

In [25]:
# Check if sample names are in the index (rows) and transpose if needed
sample_id_col = "sample_name"
grouping_col = "location"
metadata[sample_id_col] = metadata[sample_id_col].astype(str).str.strip()

# If sample names are in the index, transpose the count table so rows = ASVs and columns = samples
if df_counts.index.isin(metadata[sample_id_col]).any():
    df_counts = df_counts.T

In [26]:
# Assign Genus taxonomy to feature IDs (rows)
df_counts.index = df_tax.reindex(df_counts.index)["Genus"].fillna("Unclassified").values

In [27]:
# Compute relative abundance (%) per sample
df_genus_counts = df_counts.groupby(level=0).sum()
df_relative = (df_genus_counts.div(df_genus_counts.sum(axis=0), axis=1)) * 100

In [28]:
# Clean and map sample columns to metadata groups
df_relative.columns = df_relative.columns.astype(str).str.strip()
sample_to_group = dict(zip(metadata[sample_id_col], metadata[grouping_col]))
df_relative.columns = df_relative.columns.map(sample_to_group)

In [29]:
# Average relative abundance across biological replicates per group
df_mean = df_relative.T.groupby(level=0).mean().T

In [30]:
# Convert matrix to long format for Plotly
df_plot = df_mean.rename_axis("Genus").reset_index()
df_plot = df_plot.melt(
    id_vars="Genus",
    var_name="Location",
    value_name="Relative abundance (%)"
)
df_plot["Genus"] = df_plot["Genus"].str.replace(r"^g__", "", regex=True)

print(f"-> Success! Total rows in df_plot: {len(df_plot)}")
display(df_plot.head())

-> Success! Total rows in df_plot: 897

                               Genus Location  Relative abundance (%)
0                       Unclassified       LC               34.060980
1                        Aaosphaeria       LC                0.000000
2                         Acremonium       LC                0.054991
3                    Acrophialophora       LC                0.040927
4  Agaricomycetes_gen_Incertae_sedis       LC                0.012457

In [31]:
# Treshold comparison groupoing low abundance groups

In [32]:
thresholds = [0.1, 0.5, 1.0]
results = []

for umbral in thresholds:
    mean_abund = df_plot.groupby("Genus")["Relative abundance (%)"].mean()
    minor = mean_abund[mean_abund < umbral].index
    n_minor = len(minor)
    n_remaining = df_plot["Genus"].nunique() - n_minor + (1 if n_minor > 0 else 0)
    
    grouped_abund = (
        df_plot[df_plot["Genus"].isin(minor)]
        .groupby("Location")["Relative abundance (%)"]
        .sum()
    )
    
    row_data = {
        "Threshold (%)": umbral,
        "Genera grouped": n_minor,
        "Final categories": n_remaining
    }
    for loc, val in grouped_abund.items():
        row_data[f"{loc} (%)"] = val
        
    results.append(row_data)

comparison_table = pd.DataFrame(results).fillna(0)
print("=== THRESHOLD COMPARISON TABLE ===")
display(comparison_table.round(2))

=== THRESHOLD COMPARISON TABLE ===

   Threshold (%)  Genera grouped  Final categories  LC (%)  LL (%)  LRS (%)
0            0.1             220                80    7.78    7.28     5.41
1            0.5             278                22   15.83   21.28    20.09
2            1.0             286                14   21.89   25.78    26.94

In [33]:
# Applying 0.5% as a filter for low abundance

In [34]:
threshold = 0.5
mean_abundance = df_plot.groupby("Genus")["Relative abundance (%)"].mean()
minor_genera = mean_abundance[mean_abundance < threshold].index

df_plot_grouped = df_plot.copy()
df_plot_grouped["Genus"] = df_plot_grouped["Genus"].where(
    ~df_plot_grouped["Genus"].isin(minor_genera),
    f"Other genera (<{threshold}%)"
)

df_plot_grouped = (
    df_plot_grouped
    .groupby(["Location", "Genus"], as_index=False)
    ["Relative abundance (%)"]
    .sum()
)

print(f"-> Taxa grouped using {threshold}% threshold. Resulting categories: {df_plot_grouped['Genus'].nunique()}")

-> Taxa grouped using 0.5% threshold. Resulting categories: 22

In [35]:
# Plotting and figures

In [36]:
import plotly.express as px

colors = [
    "#A6CEE3", "#E69F00", "#009E73", "#FB9A99", "#6A3D9A", 
    "#56B4E9", "#F0E442", "#8C564B", "#B2DF8A", "#D1495B", 
    "#D55E00", "#4D9221", "#F2B8D6", "#A23BEC", "#FF6F61", 
    "#BCBD22", "#BD1100", "#17BECF", "#7F8FE8", "#006D77", 
    "#FDBF6F", "#B19429"
]

group_minor = f"Other genera (<{threshold}%)"
group_unclassified = "Unclassified"

graphic_mean_abundance = df_plot_grouped.groupby("Genus")["Relative abundance (%)"].mean()

individual_genera = (
    graphic_mean_abundance
    .drop(index=[group_minor, group_unclassified], errors="ignore")
    .sort_values(ascending=False)
    .index.tolist()
)

genus_order = []
if group_unclassified in graphic_mean_abundance.index:
    genus_order.append(group_unclassified)
if group_minor in graphic_mean_abundance.index:
    genus_order.append(group_minor)
genus_order.extend(individual_genera)

color_map = {genus: colors[i % len(colors)] for i, genus in enumerate(individual_genera)}

fig = px.bar(
    df_plot_grouped,
    x="Location",
    y="Relative abundance (%)",
    color="Genus",
    barmode="stack",
    color_discrete_map=color_map,
    category_orders={"Genus": genus_order},
    title="Mean Relative Abundance of Fungal Genera by Location",
    labels={
        "Location": "Location",
        "Relative abundance (%)": "Mean relative abundance (%)",
        "Genus": "Fungal genus"
    }
)

fig.update_traces(marker_line_width=0)

fig.for_each_trace(
    lambda trace: trace.update(
        name=f"<i>{trace.name}</i>"
        if trace.name not in [group_minor, group_unclassified]
        else trace.name
    )
)

fig.update_layout(
    template="plotly_white",
    width=1200,
    height=900,
    font=dict(size=16),
#    xaxis_title="Location",
    yaxis_title="Mean relative abundance (%)",
    yaxis=dict(range=[0, 100]),
    legend_title_text="",
    legend=dict(
        orientation="v",
        x=1.02,
        xanchor="left",
        y=1,
        yanchor="top",
        font=dict(size=14),
        itemsizing="constant",
        traceorder="reversed"
    ),
    margin=dict(l=80, r=300, t=60, b=80)
)

# Display interactive chart and export files
fig.show()

fig.write_image(filepath + "fungal_genera_abundance.pdf")
fig.write_image(filepath + "funga_genera_abundance.png", scale=3)