In [1]:
import pandas
import numpy
import plotly

print("pandas:", pandas.__version__)
print("numpy:", numpy.__version__)
print("plotly:", plotly.__version__)

pandas: 2.0.3
numpy: 1.24.4
plotly: 4.11.0

In [2]:
import sys
import copy
import pandas as pd
import numpy as np
import random

import plotly.express as px
import plotly.graph_objs as go
from plotly.subplots import make_subplots

import plotly.io as pio
pio.renderers.default = 'colab' # or 'notebook' or 'colab' or 'jupyterlab'
#pio.renderers.default = 'azure' # or 'notebook' or 'colab' or 'jupyterlab'


sys.path.append("/home/tatiana/Programas/seqDataClass")

from seqDataClass import seqObject

print("Python:", sys.version)

Python: 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0]

In [3]:
filepath = "/home/tatiana/PROYECTOS/repository/" # change by your path
filepath + "metadata.csv"

'/home/tatiana/PROYECTOS/repository/metadata.csv'

In [4]:
"metadata.csv"

'metadata.csv'

In [5]:
pd.read_csv(filepath + "metadata.csv")
df1 = pd.read_csv(filepath+"metadata.csv")
df1

,sample_name,copy,location,average,date,height,area,depth,coordinate,Chlorophyll,...,Fluoride,Chloride,Nitrate,Sulphate,recount_MM,recount_DG18,recount_SNA,recount_R2A,recount_RB,recount_MY10-12
0,its-LC1,1,LC,1,4_10_2023,3050,21000,2.1,37.05957_-3.33433,1.77,...,25,876,475.00,1713,1,1,0,2,0,0
1,its-LC2,2,LC,1,4_10_2023,3050,21000,2.1,37.05957_-3.33434,1.77,...,25,876,475.00,1713,1,1,0,2,0,0
2,its-LC3,3,LC,1,4_10_2023,3050,21000,2.1,37.05957_-3.33435,1.77,...,25,876,475.00,1713,1,1,0,2,0,0
3,its-LL1,1,LL,2,11_09_2023,2870,17700,U,37.05957_-3.33433,1.30,...,35,929,442.00,3774,0,2,2,3,0,0
4,its-LL2,2,LL,2,11_09_2023,2870,17700,U,37.05957_-3.33434,1.30,...,35,929,442.00,3774,0,2,2,3,0,0
5,its-LL3,3,LL,2,11_09_2023,2870,17700,U,37.05957_-3.33435,1.30,...,35,929,442.00,3774,0,2,2,3,0,0
6,its-LRS1,1,LRS,3,4_10_2023,2987,4200,1.6,37.052113_-3.345583,0.84,...,66,804,0.45,2252,1,0,0,2,0,1
7,its-LRS2,2,LRS,3,4_10_2023,2987,4200,1.6,37.052113_-3.345584,0.84,...,66,804,0.45,2252,1,0,0,2,0,1
8,its-LRS3,3,LRS,3,4_10_2023,2987,4200,1.6,37.052113_-3.345585,0.84,...,66,804,0.45,2252,1,0,0,2,0,1

# Modification to the format and remove of "sequence" from columns

In [6]:
# import pandas as pd

mapping = pd.read_csv(filepath + "metadata.csv")
taxonomy = pd.read_csv(filepath + "taxonomy.csv")
features = pd.read_csv(filepath + "feature_table.csv")

print("Mapping:", mapping.shape)
print("Columnas mapping:", mapping.columns.tolist())

print("Taxonomy:", taxonomy.shape)
print("Columnas taxonomy:", taxonomy.columns.tolist())

print("Features:", features.shape)
print("Primeras columnas features:", features.columns[:5].tolist())
print(features.iloc[:3, :5])

Mapping: (9, 39)
Columnas mapping: ['sample_name', 'copy', 'location', 'average', 'date', 'height', 'area', 'depth', 'coordinate', 'Chlorophyll ', 'Conductivity', 'fDOM ', 'ORP ', 'Salinity ', 'TDS ', 'pH', 'Temperature ', 'Oxigen_1', 'Oxigen_2', 'Alkalinity', 'TAC', 'filtered_volume', 'max_depth', 'sechi_depth', 'Sodium', 'Ammonium', 'Potassium ', 'Calcium ', 'Magnesium ', 'Fluoride ', 'Chloride', 'Nitrate ', 'Sulphate', 'recount_MM', 'recount_DG18', 'recount_SNA', 'recount_R2A', 'recount_RB', 'recount_MY10-12']
Taxonomy: (1559, 8)
Columnas taxonomy: ['feature-id', 'Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species']
Features: (9, 1024)
Primeras columnas features: ['Unnamed: 0', 'TCGAGTTTACAACTCCCAAAACCCCTGTGAACATACCTATCGTTGCTTCGGCGGGATCGCCCCGGCGCCTCCGGGCCCGGACCCAGGCGCCCGCCGGAGGACCCAAACTCTTGAATTTACGGTGTATCTTCTGAGTGAAACAAGCAAATAAATCA', 'CCGAGTTTACAACTCCCAAACCCCTGTGAACATACCTATCGTTGCTTCGGCGGAGTCGTCCCGGCGTCCCCCTCTCCGGAGGAGGGCCCGGACCCAGGCGCCCGCCGGAGGACCCAAACTCCTGTTTCATTTTGAGTATCTTCTGAGTAAAACAAGCAAATAAATCA', 'ACAAATCCTGCTGCAGTACCGCAAGGTGCTGTAGTATATTAACTCGGCCTGTGTCGCAAGATGCAGGCTGACTATATAAATGTGTGTAATGTAGACAATGTGTGTGTGATTAATTAGTAGA', 'AGAGAATATTGGACTTTGGTCCATTTATCTACCCATCTACACCTGTGAACTGTTTATGTGCTTCGGCACGTTTTACACAAACTTCTAAATGTAATGAATGTAATCATATTATAACAATAATA']
  Unnamed: 0  \
0    its-LC1
1    its-LC2
2    its-LC3

   TCGAGTTTACAACTCCCAAAACCCCTGTGAACATACCTATCGTTGCTTCGGCGGGATCGCCCCGGCGCCTCCGGGCCCGGACCCAGGCGCCCGCCGGAGGACCCAAACTCTTGAATTTACGGTGTATCTTCTGAGTGAAACAAGCAAATAAATCA  \
0                                                  0
1                                                325
2                                                147

   CCGAGTTTACAACTCCCAAACCCCTGTGAACATACCTATCGTTGCTTCGGCGGAGTCGTCCCGGCGTCCCCCTCTCCGGAGGAGGGCCCGGACCCAGGCGCCCGCCGGAGGACCCAAACTCCTGTTTCATTTTGAGTATCTTCTGAGTAAAACAAGCAAATAAATCA  \
0                                                  0
1                                                 87
2                                                439

   ACAAATCCTGCTGCAGTACCGCAAGGTGCTGTAGTATATTAACTCGGCCTGTGTCGCAAGATGCAGGCTGACTATATAAATGTGTGTAATGTAGACAATGTGTGTGTGATTAATTAGTAGA  \
0                                              62678
1                                             152077
2                                              39725

   AGAGAATATTGGACTTTGGTCCATTTATCTACCCATCTACACCTGTGAACTGTTTATGTGCTTCGGCACGTTTTACACAAACTTCTAAATGTAATGAATGTAATCATATTATAACAATAATA
0                                                  0
1                                                584
2                                                  8

In [7]:
import pandas as pd

taxonomy = pd.read_csv(
    filepath + "taxonomy.csv",
    sep=","
)

taxonomy = taxonomy.rename(columns={"Sequence": "feature-id"})

taxonomy.to_csv(
    filepath + "taxonomy.csv",
    index=False
)

print(taxonomy.columns.tolist())

['feature-id', 'Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species']

In [8]:
seqOne = seqObject(
    mappingFile=filepath + "metadata.csv",
    taxonomyFile=filepath + "taxonomy.csv",
    featureFile=filepath + "feature_table.csv",
    mappingSep=",",
    taxonomySep=",",
    featureSep=",",
    sampleNamesColumn="sample_name",
    featureFormat="dada2",
    taxonomyFormat="seqDataClass"
)

Initializing data loading.
Loading mapping file
Loading taxonomy
Taxonomy has some redundant features. Attempting to prune these.
Matching features between feature file and taxonomy file.
Features match.

In [9]:
seqOne.extract_rep_seq(filename = filepath + "rep_Sec_fun.csv", renameFeatures=True)

In [10]:
sample_sums = seqOne.data.sum()

sample_sums.index = seqOne.data.sum().index.to_frame(index=False)["sample_name"]

In [11]:
fig = go.Figure(go.Bar(x = sample_sums.index, y = sample_sums))

fig.show()

In [12]:
# Seq seq depth means the number of reads where to rarefied

seqOne.rarefy_to_even_depth(seqDepth=43515, seed=48) #### check the depth and adapt to the batch of samples

Removing 4 features/OTUs that no longer appear in any sample.

In [13]:
from skbio.diversity import alpha

In [14]:
for column in seqOne.data:
    print(column)

('its-LC1', 1, 'LC', 1, '4_10_2023', 3050, 21000, '2.1', '37.05957_-3.33433', 1.77, 54.25, 4.03, 267.45, 0.03, 47.0, 8.23, 11.58, 103.13, 12.04, 0.83, 4.21, 11.0, 2.1, 2.1, 3, 6.0, 236, 12711, 1222, 25, 876, 475.0, 1713, 1, 1, 0, 2, 0, 0)
('its-LC2', 2, 'LC', 1, '4_10_2023', 3050, 21000, '2.1', '37.05957_-3.33434', 1.77, 54.25, 4.03, 267.45, 0.03, 47.0, 8.23, 11.58, 103.13, 12.04, 0.83, 4.21, 11.0, 2.1, 2.1, 3, 6.0, 236, 12711, 1222, 25, 876, 475.0, 1713, 1, 1, 0, 2, 0, 0)
('its-LC3', 3, 'LC', 1, '4_10_2023', 3050, 21000, '2.1', '37.05957_-3.33435', 1.77, 54.25, 4.03, 267.45, 0.03, 47.0, 8.23, 11.58, 103.13, 12.04, 0.83, 4.21, 11.0, 2.1, 2.1, 3, 6.0, 236, 12711, 1222, 25, 876, 475.0, 1713, 1, 1, 0, 2, 0, 0)
('its-LL1', 1, 'LL', 2, '11_09_2023', 2870, 17700, 'U', '37.05957_-3.33433', 1.3, 76.29, 1.89, 311.74, 0.05, 72.0, 7.18, 8.52, 105.42, 13.78, 0.95, 4.76, 11.0, 5.0, 5.0, 4, 52.0, 309, 14947, 1052, 35, 929, 442.0, 3774, 0, 2, 2, 3, 0, 0)
('its-LL2', 2, 'LL', 2, '11_09_2023', 2870, 17700, 'U', '37.05957_-3.33434', 1.3, 76.29, 1.89, 311.74, 0.05, 72.0, 7.18, 8.52, 105.42, 13.78, 0.95, 4.76, 11.0, 5.0, 5.0, 4, 52.0, 309, 14947, 1052, 35, 929, 442.0, 3774, 0, 2, 2, 3, 0, 0)
('its-LL3', 3, 'LL', 2, '11_09_2023', 2870, 17700, 'U', '37.05957_-3.33435', 1.3, 76.29, 1.89, 311.74, 0.05, 72.0, 7.18, 8.52, 105.42, 13.78, 0.95, 4.76, 11.0, 5.0, 5.0, 4, 52.0, 309, 14947, 1052, 35, 929, 442.0, 3774, 0, 2, 2, 3, 0, 0)
('its-LRS1', 1, 'LRS', 3, '4_10_2023', 2987, 4200, '1.6', '37.052113_-3.345583', 0.84, 58.02, 3.88, 278.49, 0.03, 37.09, 8.42, 11.78, 101.43, 12.35, 0.7, 3.7, 5.5, 1.8, 1.8, 6, 0.05, 234, 10176, 1384, 66, 804, 0.45, 2252, 1, 0, 0, 2, 0, 1)
('its-LRS2', 2, 'LRS', 3, '4_10_2023', 2987, 4200, '1.6', '37.052113_-3.345584', 0.84, 58.02, 3.88, 278.49, 0.03, 37.09, 8.42, 11.78, 101.43, 12.35, 0.7, 3.7, 5.5, 1.8, 1.8, 6, 0.05, 234, 10176, 1384, 66, 804, 0.45, 2252, 1, 0, 0, 2, 0, 1)
('its-LRS3', 3, 'LRS', 3, '4_10_2023', 2987, 4200, '1.6', '37.052113_-3.345585', 0.84, 58.02, 3.88, 278.49, 0.03, 37.09, 8.42, 11.78, 101.43, 12.35, 0.7, 3.7, 5.5, 1.8, 1.8, 6, 0.05, 234, 10176, 1384, 66, 804, 0.45, 2252, 1, 0, 0, 2, 0, 1)

In [15]:
seqOne.data[column]

feature-id   Kingdom   Phylum            Class                                Order                                Family                               Genus                                Species        tax_rank
feature0     k__Fungi  p__Ascomycota     c__Sordariomycetes                   o__Hypocreales                       f__Nectriaceae                       g__Paracremonium                     NaN            0.0         18816
feature1     k__Fungi  p__Ascomycota     c__Sordariomycetes                   o__Hypocreales                       f__Nectriaceae                       g__Cosmospora                        NaN            1.0         15129
feature2     k__Fungi  p__Rozellomycota  c__Rozellomycota_cls_Incertae_sedis  o__Rozellomycota_ord_Incertae_sedis  f__Rozellomycota_fam_Incertae_sedis  g__Rozellomycota_gen_Incertae_sedis  NaN            2.0            63
feature3     k__Fungi  p__Basidiomycota  c__Tremellomycetes                   o__Tremellales                       f__Cryptococcaceae                   g__Cryptococcus                      s__neoformans  3.0             0
feature4     k__Fungi  NaN               NaN                                  NaN                                  NaN                                  NaN                                  NaN            4.0             9
                                                                                                                                                                                                                        ...
feature1018  k__Fungi  NaN               NaN                                  NaN                                  NaN                                  NaN                                  NaN            1018.0          0
feature1019  k__Fungi  NaN               NaN                                  NaN                                  NaN                                  NaN                                  NaN            1019.0          0
feature1020  k__Fungi  p__Ascomycota     c__Sordariomycetes                   o__Hypocreales                       f__Bionectriaceae                    g__Acremonium                        s__tubakii     1020.0          0
feature1021  k__Fungi  p__Ascomycota     c__Sordariomycetes                   o__Chaetosphaeriales                 f__Chaetosphaeriaceae                g__Chaetosphaeria                    s__ciliata     1021.0          0
feature1022  k__Fungi  p__Ascomycota     c__Leotiomycetes                     o__Helotiales                        f__Helotiaceae                       g__Glarea                            NaN            1022.0          0
Name: (its-LRS3, 3, LRS, 3, 4_10_2023, 2987, 4200, 1.6, 37.052113_-3.345585, 0.84, 58.02, 3.88, 278.49, 0.03, 37.09, 8.42, 11.78, 101.43, 12.35, 0.7, 3.7, 5.5, 1.8, 1.8, 6, 0.05, 234, 10176, 1384, 66, 804, 0.45, 2252, 1, 0, 0, 2, 0, 1), Length: 1019, dtype: int64

In [16]:
for column in seqOne.data:
    print(column)
    print(seqOne.data[column])
    break

('its-LC1', 1, 'LC', 1, '4_10_2023', 3050, 21000, '2.1', '37.05957_-3.33433', 1.77, 54.25, 4.03, 267.45, 0.03, 47.0, 8.23, 11.58, 103.13, 12.04, 0.83, 4.21, 11.0, 2.1, 2.1, 3, 6.0, 236, 12711, 1222, 25, 876, 475.0, 1713, 1, 1, 0, 2, 0, 0)
feature-id   Kingdom   Phylum            Class                                Order                                Family                               Genus                                Species        tax_rank
feature0     k__Fungi  p__Ascomycota     c__Sordariomycetes                   o__Hypocreales                       f__Nectriaceae                       g__Paracremonium                     NaN            0.0            0
feature1     k__Fungi  p__Ascomycota     c__Sordariomycetes                   o__Hypocreales                       f__Nectriaceae                       g__Cosmospora                        NaN            1.0            0
feature2     k__Fungi  p__Rozellomycota  c__Rozellomycota_cls_Incertae_sedis  o__Rozellomycota_ord_Incertae_sedis  f__Rozellomycota_fam_Incertae_sedis  g__Rozellomycota_gen_Incertae_sedis  NaN            2.0         9151
feature3     k__Fungi  p__Basidiomycota  c__Tremellomycetes                   o__Tremellales                       f__Cryptococcaceae                   g__Cryptococcus                      s__neoformans  3.0            0
feature4     k__Fungi  NaN               NaN                                  NaN                                  NaN                                  NaN                                  NaN            4.0         4621
                                                                                                                                                                                                                        ...
feature1018  k__Fungi  NaN               NaN                                  NaN                                  NaN                                  NaN                                  NaN            1018.0         0
feature1019  k__Fungi  NaN               NaN                                  NaN                                  NaN                                  NaN                                  NaN            1019.0         0
feature1020  k__Fungi  p__Ascomycota     c__Sordariomycetes                   o__Hypocreales                       f__Bionectriaceae                    g__Acremonium                        s__tubakii     1020.0         0
feature1021  k__Fungi  p__Ascomycota     c__Sordariomycetes                   o__Chaetosphaeriales                 f__Chaetosphaeriaceae                g__Chaetosphaeria                    s__ciliata     1021.0         0
feature1022  k__Fungi  p__Ascomycota     c__Leotiomycetes                     o__Helotiales                        f__Helotiaceae                       g__Glarea                            NaN            1022.0        21
Name: (its-LC1, 1, LC, 1, 4_10_2023, 3050, 21000, 2.1, 37.05957_-3.33433, 1.77, 54.25, 4.03, 267.45, 0.03, 47.0, 8.23, 11.58, 103.13, 12.04, 0.83, 4.21, 11.0, 2.1, 2.1, 3, 6.0, 236, 12711, 1222, 25, 876, 475.0, 1713, 1, 1, 0, 2, 0, 0), Length: 1019, dtype: int64

In [17]:
alpha.observed_otus(seqOne.data[column])

233

In [18]:
for column in seqOne.data:
    print(column)
    #print(seqOne.data[column])
    print(alpha.observed_otus(seqOne.data[column]))

('its-LC1', 1, 'LC', 1, '4_10_2023', 3050, 21000, '2.1', '37.05957_-3.33433', 1.77, 54.25, 4.03, 267.45, 0.03, 47.0, 8.23, 11.58, 103.13, 12.04, 0.83, 4.21, 11.0, 2.1, 2.1, 3, 6.0, 236, 12711, 1222, 25, 876, 475.0, 1713, 1, 1, 0, 2, 0, 0)
233
('its-LC2', 2, 'LC', 1, '4_10_2023', 3050, 21000, '2.1', '37.05957_-3.33434', 1.77, 54.25, 4.03, 267.45, 0.03, 47.0, 8.23, 11.58, 103.13, 12.04, 0.83, 4.21, 11.0, 2.1, 2.1, 3, 6.0, 236, 12711, 1222, 25, 876, 475.0, 1713, 1, 1, 0, 2, 0, 0)
357
('its-LC3', 3, 'LC', 1, '4_10_2023', 3050, 21000, '2.1', '37.05957_-3.33435', 1.77, 54.25, 4.03, 267.45, 0.03, 47.0, 8.23, 11.58, 103.13, 12.04, 0.83, 4.21, 11.0, 2.1, 2.1, 3, 6.0, 236, 12711, 1222, 25, 876, 475.0, 1713, 1, 1, 0, 2, 0, 0)
188
('its-LL1', 1, 'LL', 2, '11_09_2023', 2870, 17700, 'U', '37.05957_-3.33433', 1.3, 76.29, 1.89, 311.74, 0.05, 72.0, 7.18, 8.52, 105.42, 13.78, 0.95, 4.76, 11.0, 5.0, 5.0, 4, 52.0, 309, 14947, 1052, 35, 929, 442.0, 3774, 0, 2, 2, 3, 0, 0)
280
('its-LL2', 2, 'LL', 2, '11_09_2023', 2870, 17700, 'U', '37.05957_-3.33434', 1.3, 76.29, 1.89, 311.74, 0.05, 72.0, 7.18, 8.52, 105.42, 13.78, 0.95, 4.76, 11.0, 5.0, 5.0, 4, 52.0, 309, 14947, 1052, 35, 929, 442.0, 3774, 0, 2, 2, 3, 0, 0)
128
('its-LL3', 3, 'LL', 2, '11_09_2023', 2870, 17700, 'U', '37.05957_-3.33435', 1.3, 76.29, 1.89, 311.74, 0.05, 72.0, 7.18, 8.52, 105.42, 13.78, 0.95, 4.76, 11.0, 5.0, 5.0, 4, 52.0, 309, 14947, 1052, 35, 929, 442.0, 3774, 0, 2, 2, 3, 0, 0)
243
('its-LRS1', 1, 'LRS', 3, '4_10_2023', 2987, 4200, '1.6', '37.052113_-3.345583', 0.84, 58.02, 3.88, 278.49, 0.03, 37.09, 8.42, 11.78, 101.43, 12.35, 0.7, 3.7, 5.5, 1.8, 1.8, 6, 0.05, 234, 10176, 1384, 66, 804, 0.45, 2252, 1, 0, 0, 2, 0, 1)
101
('its-LRS2', 2, 'LRS', 3, '4_10_2023', 2987, 4200, '1.6', '37.052113_-3.345584', 0.84, 58.02, 3.88, 278.49, 0.03, 37.09, 8.42, 11.78, 101.43, 12.35, 0.7, 3.7, 5.5, 1.8, 1.8, 6, 0.05, 234, 10176, 1384, 66, 804, 0.45, 2252, 1, 0, 0, 2, 0, 1)
142
('its-LRS3', 3, 'LRS', 3, '4_10_2023', 2987, 4200, '1.6', '37.052113_-3.345585', 0.84, 58.02, 3.88, 278.49, 0.03, 37.09, 8.42, 11.78, 101.43, 12.35, 0.7, 3.7, 5.5, 1.8, 1.8, 6, 0.05, 234, 10176, 1384, 66, 804, 0.45, 2252, 1, 0, 0, 2, 0, 1)
130

In [19]:
for column in seqOne.data:
   
    print(f"OTUs content in {column[0]}:{alpha.observed_otus(seqOne.data[column])}")

OTUs content in its-LC1:233
OTUs content in its-LC2:357
OTUs content in its-LC3:188
OTUs content in its-LL1:280
OTUs content in its-LL2:128
OTUs content in its-LL3:243
OTUs content in its-LRS1:101
OTUs content in its-LRS2:142
OTUs content in its-LRS3:130

In [20]:
seqOne.data

,,,,,,,,sample_name,its-LC1,its-LC2,its-LC3,its-LL1,its-LL2,its-LL3,its-LRS1,its-LRS2,its-LRS3
,,,,,,,,copy,1,2,3,1,2,3,1,2,3
,,,,,,,,location,LC,LC,LC,LL,LL,LL,LRS,LRS,LRS
,,,,,,,,average,1,1,1,2,2,2,3,3,3
,,,,,,,,date,4_10_2023,4_10_2023,4_10_2023,11_09_2023,11_09_2023,11_09_2023,4_10_2023,4_10_2023,4_10_2023
,,,,,,,,height,3050,3050,3050,2870,2870,2870,2987,2987,2987
,,,,,,,,area,21000,21000,21000,17700,17700,17700,4200,4200,4200
,,,,,,,,depth,2.1,2.1,2.1,U,U,U,1.6,1.6,1.6
,,,,,,,,coordinate,37.05957_-3.33433,37.05957_-3.33434,37.05957_-3.33435,37.05957_-3.33433,37.05957_-3.33434,37.05957_-3.33435,37.052113_-3.345583,37.052113_-3.345584,37.052113_-3.345585
,,,,,,,,Chlorophyll,1.77,1.77,1.77,1.30,1.30,1.30,0.84,0.84,0.84
,,,,,,,,Conductivity,54.25,54.25,54.25,76.29,76.29,76.29,58.02,58.02,58.02
,,,,,,,,fDOM,4.03,4.03,4.03,1.89,1.89,1.89,3.88,3.88,3.88
,,,,,,,,ORP,267.45,267.45,267.45,311.74,311.74,311.74,278.49,278.49,278.49
,,,,,,,,Salinity,0.03,0.03,0.03,0.05,0.05,0.05,0.03,0.03,0.03
,,,,,,,,TDS,47.00,47.00,47.00,72.00,72.00,72.00,37.09,37.09,37.09
,,,,,,,,pH,8.23,8.23,8.23,7.18,7.18,7.18,8.42,8.42,8.42
,,,,,,,,Temperature,11.58,11.58,11.58,8.52,8.52,8.52,11.78,11.78,11.78
,,,,,,,,Oxigen_1,103.13,103.13,103.13,105.42,105.42,105.42,101.43,101.43,101.43
,,,,,,,,Oxigen_2,12.04,12.04,12.04,13.78,13.78,13.78,12.35,12.35,12.35
,,,,,,,,Alkalinity,0.83,0.83,0.83,0.95,0.95,0.95,0.70,0.70,0.70
,,,,,,,,TAC,4.21,4.21,4.21,4.76,4.76,4.76,3.70,3.70,3.70
,,,,,,,,filtered_volume,11.0,11.0,11.0,11.0,11.0,11.0,5.5,5.5,5.5
,,,,,,,,max_depth,2.1,2.1,2.1,5.0,5.0,5.0,1.8,1.8,1.8
,,,,,,,,sechi_depth,2.1,2.1,2.1,5.0,5.0,5.0,1.8,1.8,1.8
,,,,,,,,Sodium,3,3,3,4,4,4,6,6,6
,,,,,,,,Ammonium,6.00,6.00,6.00,52.00,52.00,52.00,0.05,0.05,0.05
,,,,,,,,Potassium,236,236,236,309,309,309,234,234,234
,,,,,,,,Calcium,12711,12711,12711,14947,14947,14947,10176,10176,10176
,,,,,,,,Magnesium,1222,1222,1222,1052,1052,1052,1384,1384,1384
,,,,,,,,Fluoride,25,25,25,35,35,35,66,66,66
,,,,,,,,Chloride,876,876,876,929,929,929,804,804,804
,,,,,,,,Nitrate,475.00,475.00,475.00,442.00,442.00,442.00,0.45,0.45,0.45
,,,,,,,,Sulphate,1713,1713,1713,3774,3774,3774,2252,2252,2252
,,,,,,,,recount_MM,1,1,1,0,0,0,1,1,1
,,,,,,,,recount_DG18,1,1,1,2,2,2,0,0,0
,,,,,,,,recount_SNA,0,0,0,2,2,2,0,0,0
,,,,,,,,recount_R2A,2,2,2,3,3,3,2,2,2
,,,,,,,,recount_RB,0,0,0,0,0,0,0,0,0
,,,,,,,,recount_MY10-12,0,0,0,0,0,0,1,1,1
feature-id,Kingdom,Phylum,Class,Order,Family,Genus,Species,tax_rank,,,,,,,,,
feature0,k__Fungi,p__Ascomycota,c__Sordariomycetes,o__Hypocreales,f__Nectriaceae,g__Paracremonium,NaN,0.0,0,32,32,2,9857,1871,0,0,18816
feature1,k__Fungi,p__Ascomycota,c__Sordariomycetes,o__Hypocreales,f__Nectriaceae,g__Cosmospora,NaN,1.0,0,7,89,0,7274,858,0,272,15129
feature2,k__Fungi,p__Rozellomycota,c__Rozellomycota_cls_Incertae_sedis,o__Rozellomycota_ord_Incertae_sedis,f__Rozellomycota_fam_Incertae_sedis,g__Rozellomycota_gen_Incertae_sedis,NaN,2.0,9151,11089,8985,597,0,434,0,0,63
feature3,k__Fungi,p__Basidiomycota,c__Tremellomycetes,o__Tremellales,f__Cryptococcaceae,g__Cryptococcus,s__neoformans,3.0,0,42,1,0,100,27,0,0,0
feature4,k__Fungi,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4621,3960,1868,463,0,647,0,0,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
feature1018,k__Fungi,NaN,NaN,NaN,NaN,NaN,NaN,1018.0,0,0,0,20,0,0,0,0,0
feature1019,k__Fungi,NaN,NaN,NaN,NaN,NaN,NaN,1019.0,0,0,0,28,0,0,0,0,0
feature1020,k__Fungi,p__Ascomycota,c__Sordariomycetes,o__Hypocreales,f__Bionectriaceae,g__Acremonium,s__tubakii,1020.0,0,0,0,19,0,7,0,0,0
feature1021,k__Fungi,p__Ascomycota,c__Sordariomycetes,o__Chaetosphaeriales,f__Chaetosphaeriaceae,g__Chaetosphaeria,s__ciliata,1021.0,0,0,0,0,0,20,0,0,0
feature1022,k__Fungi,p__Ascomycota,c__Leotiomycetes,o__Helotiales,f__Helotiaceae,g__Glarea,NaN,1022.0,21,0,0,0,0,0,0,0,0

In [21]:
seqOne.data.columns.to_frame(index = False)

,sample_name,copy,location,average,date,height,area,depth,coordinate,Chlorophyll,...,Fluoride,Chloride,Nitrate,Sulphate,recount_MM,recount_DG18,recount_SNA,recount_R2A,recount_RB,recount_MY10-12
0,its-LC1,1,LC,1,4_10_2023,3050,21000,2.1,37.05957_-3.33433,1.77,...,25,876,475.00,1713,1,1,0,2,0,0
1,its-LC2,2,LC,1,4_10_2023,3050,21000,2.1,37.05957_-3.33434,1.77,...,25,876,475.00,1713,1,1,0,2,0,0
2,its-LC3,3,LC,1,4_10_2023,3050,21000,2.1,37.05957_-3.33435,1.77,...,25,876,475.00,1713,1,1,0,2,0,0
3,its-LL1,1,LL,2,11_09_2023,2870,17700,U,37.05957_-3.33433,1.30,...,35,929,442.00,3774,0,2,2,3,0,0
4,its-LL2,2,LL,2,11_09_2023,2870,17700,U,37.05957_-3.33434,1.30,...,35,929,442.00,3774,0,2,2,3,0,0
5,its-LL3,3,LL,2,11_09_2023,2870,17700,U,37.05957_-3.33435,1.30,...,35,929,442.00,3774,0,2,2,3,0,0
6,its-LRS1,1,LRS,3,4_10_2023,2987,4200,1.6,37.052113_-3.345583,0.84,...,66,804,0.45,2252,1,0,0,2,0,1
7,its-LRS2,2,LRS,3,4_10_2023,2987,4200,1.6,37.052113_-3.345584,0.84,...,66,804,0.45,2252,1,0,0,2,0,1
8,its-LRS3,3,LRS,3,4_10_2023,2987,4200,1.6,37.052113_-3.345585,0.84,...,66,804,0.45,2252,1,0,0,2,0,1

In [22]:
for column in seqOne.data:
   
    print(f"Shannon index in {column[0]}:{alpha.shannon(seqOne.data[column])}")

Shannon index in its-LC1:5.676586871917373
Shannon index in its-LC2:5.879325025616516
Shannon index in its-LC3:5.960813401147795
Shannon index in its-LL1:6.390642915456355
Shannon index in its-LL2:5.06345779448864
Shannon index in its-LL3:6.362366402725819
Shannon index in its-LRS1:6.104305080320461
Shannon index in its-LRS2:5.817130575683793
Shannon index in its-LRS3:2.4461652717110915

In [23]:
for column in seqOne.data:
   
    print(f"Pielou index in {column[0]}:{alpha.pielou_e(seqOne.data[column])}")

Pielou index in its-LC1:0.7218276332098347
Pielou index in its-LC2:0.6933345962461298
Pielou index in its-LC3:0.7890321390321704
Pielou index in its-LL1:0.7861262674869938
Pielou index in its-LL2:0.7233511134983771
Pielou index in its-LL3:0.8028412533206243
Pielou index in its-LRS1:0.9168085297581433
Pielou index in its-LRS2:0.813613471700911
Pielou index in its-LRS3:0.3483390982700695

In [24]:
for column in seqOne.data:
   
    print(f"Simpson index in {column[0]}:{alpha.simpson(seqOne.data[column])}")

Simpson index in its-LC1:0.9333718598040889
Simpson index in its-LC2:0.919520435956654
Simpson index in its-LC3:0.9453579733857511
Simpson index in its-LL1:0.970761480695658
Simpson index in its-LL2:0.9113026286307546
Simpson index in its-LL3:0.9708912091539342
Simpson index in its-LRS1:0.9778249229567625
Simpson index in its-LRS2:0.9508903570530931
Simpson index in its-LRS3:0.685102003296471

In [25]:
for column in seqOne.data:
    print(f"Chao1 index in {column[0]}: {alpha.chao1(seqOne.data[column])}")

Chao1 index in its-LC1: 233.5
Chao1 index in its-LC2: 357.0
Chao1 index in its-LC3: 188.0
Chao1 index in its-LL1: 281.5
Chao1 index in its-LL2: 128.0
Chao1 index in its-LL3: 244.5
Chao1 index in its-LRS1: 101.0
Chao1 index in its-LRS2: 142.0
Chao1 index in its-LRS3: 132.625

In [26]:
for column in seqOne.data:
    print(f"Feature count in {column[0]}: {alpha.observed_otus(seqOne.data[column])}")

Feature count in its-LC1: 233
Feature count in its-LC2: 357
Feature count in its-LC3: 188
Feature count in its-LL1: 280
Feature count in its-LL2: 128
Feature count in its-LL3: 243
Feature count in its-LRS1: 101
Feature count in its-LRS2: 142
Feature count in its-LRS3: 130

In [27]:
Feature_counts = {}
Shannon = {}
Pielou = {}
Simpson = {}
Chao1 = {}

for column in seqOne.data:
    muestra = column[0]
    counts = seqOne.data[column]

    Feature_counts[muestra] = alpha.observed_otus(counts)
    Shannon[muestra] = alpha.shannon(counts)
    Pielou[muestra] = alpha.pielou_e(counts)
    Simpson[muestra] = alpha.simpson_e(counts)
    Chao1[muestra] = alpha.chao1(counts)

    print(f"Feature count in {muestra}: {Feature_counts[muestra]}")
    print(f"Shannon index in {muestra}: {Shannon[muestra]}")
    print(f"Pielou index in {muestra}: {Pielou[muestra]}")
    print(f"Simpson index in {muestra}: {Simpson[muestra]}")
    print(f"Chao1 index in {muestra}: {Chao1[muestra]}")
    print("-" * 40)

Feature count in its-LC1: 233
Shannon index in its-LC1: 5.676586871917373
Pielou index in its-LC1: 0.7218276332098347
Simpson index in its-LC1: 0.06441490758923535
Chao1 index in its-LC1: 233.5
----------------------------------------
Feature count in its-LC2: 357
Shannon index in its-LC2: 5.879325025616516
Pielou index in its-LC2: 0.6933345962461298
Simpson index in its-LC2: 0.03480536309404705
Chao1 index in its-LC2: 357.0
----------------------------------------
Feature count in its-LC3: 188
Shannon index in its-LC3: 5.960813401147795
Pielou index in its-LC3: 0.7890321390321704
Simpson index in its-LC3: 0.0973453816733648
Chao1 index in its-LC3: 188.0
----------------------------------------
Feature count in its-LL1: 280
Shannon index in its-LL1: 6.390642915456355
Pielou index in its-LL1: 0.7861262674869938
Simpson index in its-LL1: 0.12214806551090346
Chao1 index in its-LL1: 281.5
----------------------------------------
Feature count in its-LL2: 128
Shannon index in its-LL2: 5.06345779448864
Pielou index in its-LL2: 0.7233511134983771
Simpson index in its-LL2: 0.08808040057327877
Chao1 index in its-LL2: 128.0
----------------------------------------
Feature count in its-LL3: 243
Shannon index in its-LL3: 6.362366402725819
Pielou index in its-LL3: 0.8028412533206243
Simpson index in its-LL3: 0.14137400482249018
Chao1 index in its-LL3: 244.5
----------------------------------------
Feature count in its-LRS1: 101
Shannon index in its-LRS1: 6.104305080320461
Pielou index in its-LRS1: 0.9168085297581433
Simpson index in its-LRS1: 0.4464918015709571
Chao1 index in its-LRS1: 101.0
----------------------------------------
Feature count in its-LRS2: 142
Shannon index in its-LRS2: 5.817130575683793
Pielou index in its-LRS2: 0.813613471700911
Simpson index in its-LRS2: 0.1433985893308211
Chao1 index in its-LRS2: 142.0
----------------------------------------
Feature count in its-LRS3: 130
Shannon index in its-LRS3: 2.4461652717110915
Pielou index in its-LRS3: 0.3483390982700695
Simpson index in its-LRS3: 0.024427934673556743
Chao1 index in its-LRS3: 132.625
----------------------------------------

In [28]:
Feature_counts

{'its-LC1': 233,
 'its-LC2': 357,
 'its-LC3': 188,
 'its-LL1': 280,
 'its-LL2': 128,
 'its-LL3': 243,
 'its-LRS1': 101,
 'its-LRS2': 142,
 'its-LRS3': 130}

In [29]:
Shannon

{'its-LC1': 5.676586871917373,
 'its-LC2': 5.879325025616516,
 'its-LC3': 5.960813401147795,
 'its-LL1': 6.390642915456355,
 'its-LL2': 5.06345779448864,
 'its-LL3': 6.362366402725819,
 'its-LRS1': 6.104305080320461,
 'its-LRS2': 5.817130575683793,
 'its-LRS3': 2.4461652717110915}

In [30]:
Pielou

{'its-LC1': 0.7218276332098347,
 'its-LC2': 0.6933345962461298,
 'its-LC3': 0.7890321390321704,
 'its-LL1': 0.7861262674869938,
 'its-LL2': 0.7233511134983771,
 'its-LL3': 0.8028412533206243,
 'its-LRS1': 0.9168085297581433,
 'its-LRS2': 0.813613471700911,
 'its-LRS3': 0.3483390982700695}

In [31]:
Simpson

{'its-LC1': 0.06441490758923535,
 'its-LC2': 0.03480536309404705,
 'its-LC3': 0.0973453816733648,
 'its-LL1': 0.12214806551090346,
 'its-LL2': 0.08808040057327877,
 'its-LL3': 0.14137400482249018,
 'its-LRS1': 0.4464918015709571,
 'its-LRS2': 0.1433985893308211,
 'its-LRS3': 0.024427934673556743}

In [32]:
Chao1

{'its-LC1': 233.5,
 'its-LC2': 357.0,
 'its-LC3': 188.0,
 'its-LL1': 281.5,
 'its-LL2': 128.0,
 'its-LL3': 244.5,
 'its-LRS1': 101.0,
 'its-LRS2': 142.0,
 'its-LRS3': 132.625}

In [33]:
metadata = seqOne.data.columns.to_frame(index = False)
metadata

,sample_name,copy,location,average,date,height,area,depth,coordinate,Chlorophyll,...,Fluoride,Chloride,Nitrate,Sulphate,recount_MM,recount_DG18,recount_SNA,recount_R2A,recount_RB,recount_MY10-12
0,its-LC1,1,LC,1,4_10_2023,3050,21000,2.1,37.05957_-3.33433,1.77,...,25,876,475.00,1713,1,1,0,2,0,0
1,its-LC2,2,LC,1,4_10_2023,3050,21000,2.1,37.05957_-3.33434,1.77,...,25,876,475.00,1713,1,1,0,2,0,0
2,its-LC3,3,LC,1,4_10_2023,3050,21000,2.1,37.05957_-3.33435,1.77,...,25,876,475.00,1713,1,1,0,2,0,0
3,its-LL1,1,LL,2,11_09_2023,2870,17700,U,37.05957_-3.33433,1.30,...,35,929,442.00,3774,0,2,2,3,0,0
4,its-LL2,2,LL,2,11_09_2023,2870,17700,U,37.05957_-3.33434,1.30,...,35,929,442.00,3774,0,2,2,3,0,0
5,its-LL3,3,LL,2,11_09_2023,2870,17700,U,37.05957_-3.33435,1.30,...,35,929,442.00,3774,0,2,2,3,0,0
6,its-LRS1,1,LRS,3,4_10_2023,2987,4200,1.6,37.052113_-3.345583,0.84,...,66,804,0.45,2252,1,0,0,2,0,1
7,its-LRS2,2,LRS,3,4_10_2023,2987,4200,1.6,37.052113_-3.345584,0.84,...,66,804,0.45,2252,1,0,0,2,0,1
8,its-LRS3,3,LRS,3,4_10_2023,2987,4200,1.6,37.052113_-3.345585,0.84,...,66,804,0.45,2252,1,0,0,2,0,1

In [34]:
metadata["sample_name"].map(Shannon)

0    5.676587
1    5.879325
2    5.960813
3    6.390643
4    5.063458
5    6.362366
6    6.104305
7    5.817131
8    2.446165
Name: sample_name, dtype: float64

In [35]:
metadata["Feature_counts"] = metadata["sample_name"].map(Feature_counts)
metadata["Shannon index"] = metadata["sample_name"].map(Shannon)
metadata["Pielou index"] = metadata["sample_name"].map(Pielou)
metadata["Simpson index"] = metadata["sample_name"].map(Simpson)
metadata["Chao1 index"] = metadata["sample_name"].map(Chao1)


metadata

,sample_name,copy,location,average,date,height,area,depth,coordinate,Chlorophyll,...,recount_DG18,recount_SNA,recount_R2A,recount_RB,recount_MY10-12,Feature_counts,Shannon index,Pielou index,Simpson index,Chao1 index
0,its-LC1,1,LC,1,4_10_2023,3050,21000,2.1,37.05957_-3.33433,1.77,...,1,0,2,0,0,233,5.676587,0.721828,0.064415,233.500
1,its-LC2,2,LC,1,4_10_2023,3050,21000,2.1,37.05957_-3.33434,1.77,...,1,0,2,0,0,357,5.879325,0.693335,0.034805,357.000
2,its-LC3,3,LC,1,4_10_2023,3050,21000,2.1,37.05957_-3.33435,1.77,...,1,0,2,0,0,188,5.960813,0.789032,0.097345,188.000
3,its-LL1,1,LL,2,11_09_2023,2870,17700,U,37.05957_-3.33433,1.30,...,2,2,3,0,0,280,6.390643,0.786126,0.122148,281.500
4,its-LL2,2,LL,2,11_09_2023,2870,17700,U,37.05957_-3.33434,1.30,...,2,2,3,0,0,128,5.063458,0.723351,0.088080,128.000
5,its-LL3,3,LL,2,11_09_2023,2870,17700,U,37.05957_-3.33435,1.30,...,2,2,3,0,0,243,6.362366,0.802841,0.141374,244.500
6,its-LRS1,1,LRS,3,4_10_2023,2987,4200,1.6,37.052113_-3.345583,0.84,...,0,0,2,0,1,101,6.104305,0.916809,0.446492,101.000
7,its-LRS2,2,LRS,3,4_10_2023,2987,4200,1.6,37.052113_-3.345584,0.84,...,0,0,2,0,1,142,5.817131,0.813613,0.143399,142.000
8,its-LRS3,3,LRS,3,4_10_2023,2987,4200,1.6,37.052113_-3.345585,0.84,...,0,0,2,0,1,130,2.446165,0.348339,0.024428,132.625

In [36]:
# Export
metadata.to_csv("alphadiversity-fungi-table.csv", index=False)

In [37]:
import pandas as pd

filepath = "/home/tatiana/PROYECTOS/fungil/analysis/"

diversidad = pd.read_csv(
    filepath + "alphadiversity-fungi-table.csv"
)

print(diversidad.head())
print(diversidad.columns)

  sample_name  copy location  average        date  height   area depth  \
0     its-LC1     1       LC        1   4_10_2023    3050  21000   2.1
1     its-LC2     2       LC        1   4_10_2023    3050  21000   2.1
2     its-LC3     3       LC        1   4_10_2023    3050  21000   2.1
3     its-LL1     1       LL        2  11_09_2023    2870  17700     U
4     its-LL2     2       LL        2  11_09_2023    2870  17700     U

          coordinate  Chlorophyll   ...  recount_DG18  recount_SNA  \
0  37.05957_-3.33433          1.77  ...             1            0
1  37.05957_-3.33434          1.77  ...             1            0
2  37.05957_-3.33435          1.77  ...             1            0
3  37.05957_-3.33433          1.30  ...             2            2
4  37.05957_-3.33434          1.30  ...             2            2

   recount_R2A  recount_RB  recount_MY10-12  Feature_counts  Shannon index  \
0            2           0                0             233       5.676587
1            2           0                0             357       5.879325
2            2           0                0             188       5.960813
3            3           0                0             280       6.390643
4            3           0                0             128       5.063458

   Pielou index  Simpson index  Chao1 index
0      0.721828       0.064415        233.5
1      0.693335       0.034805        357.0
2      0.789032       0.097345        188.0
3      0.786126       0.122148        281.5
4      0.723351       0.088080        128.0

[5 rows x 44 columns]
Index(['sample_name', 'copy', 'location', 'average', 'date', 'height', 'area',
       'depth', 'coordinate', 'Chlorophyll ', 'Conductivity', 'fDOM ', 'ORP ',
       'Salinity ', 'TDS ', 'pH', 'Temperature ', 'Oxigen_1', 'Oxigen_2',
       'Alkalinity', 'TAC', 'filtered_volume', 'max_depth', 'sechi_depth',
       'Sodium', 'Ammonium', 'Potassium ', 'Calcium ', 'Magnesium ',
       'Fluoride ', 'Chloride', 'Nitrate ', 'Sulphate', 'recount_MM',
       'recount_DG18', 'recount_SNA', 'recount_R2A', 'recount_RB',
       'recount_MY10-12', 'Feature_counts', 'Shannon index', 'Pielou index',
       'Simpson index', 'Chao1 index'],
      dtype='object')

In [38]:
import pandas as pd
import numpy as np

filepath = "/home/tatiana/PROYECTOS/fungil/analysis/"

diversidad = pd.read_csv(
    filepath + "alphadiversity-fungi-table.csv"
)

indices = [
    "Shannon index",
    "Feature_counts",
    "Pielou index",
    "Simpson index",
    "Chao1 index"
]

# Resumir las réplicas técnicas de cada muestra ambiental
resumen = diversidad.groupby(
    ["location", "date"]
)[indices].agg(["mean", "std"])

print(resumen)

                    Shannon index           Feature_counts             \
                             mean       std           mean        std
location date
LC       4_10_2023       5.838908  0.146360     259.333333  87.523330
LL       11_09_2023      5.938822  0.758220     217.000000  79.265377
LRS      4_10_2023       4.789200  2.034202     124.333333  21.079216

                    Pielou index           Simpson index            \
                            mean       std          mean       std
location date
LC       4_10_2023      0.734731  0.049136      0.065522  0.031285
LL       11_09_2023     0.770773  0.041910      0.117201  0.026989
LRS      4_10_2023      0.692920  0.302844      0.204773  0.217623

                    Chao1 index
                           mean        std
location date
LC       4_10_2023   259.500000  87.448556
LL       11_09_2023  218.000000  80.107740
LRS      4_10_2023   125.208333  21.482672

In [39]:
for indice in indices:
    media = diversidad.groupby(
        ["location", "date"]
    )[indice].mean()

    desviacion = diversidad.groupby(
        ["location", "date"]
    )[indice].std()

    cv = (desviacion / media) * 100

    print(f"\n{indice}")
    print("Coeficiente de variación (%):")
    print(cv)

Shannon index
Coeficiente de variación (%):
location  date
LC        4_10_2023      2.506636
LL        11_09_2023    12.767174
LRS       4_10_2023     42.474771
Name: Shannon index, dtype: float64

Feature_counts
Coeficiente de variación (%):
location  date
LC        4_10_2023     33.749356
LL        11_09_2023    36.527824
LRS       4_10_2023     16.953793
Name: Feature_counts, dtype: float64

Pielou index
Coeficiente de variación (%):
location  date
LC        4_10_2023      6.687669
LL        11_09_2023     5.437426
LRS       4_10_2023     43.705456
Name: Pielou index, dtype: float64

Simpson index
Coeficiente de variación (%):
location  date
LC        4_10_2023      47.746950
LL        11_09_2023     23.028032
LRS       4_10_2023     106.275133
Name: Simpson index, dtype: float64

Chao1 index
Coeficiente de variación (%):
location  date
LC        4_10_2023     33.698866
LL        11_09_2023    36.746670
LRS       4_10_2023     17.157542
Name: Chao1 index, dtype: float64

In [40]:
import pandas as pd

filepath = "/home/tatiana/PROYECTOS/lagunas/fungi/analysis/"

diversidad = pd.read_csv(
    filepath + "alphadiversity-fungi-table.csv"
)

# Índices de diversidad alfa
indices = [
    "Shannon index",
    "Feature_counts",
    "Pielou index",
    "Simpson index",
    "Chao1 index"
]

# Agrupar las réplicas técnicas por muestra ambiental
grupos = diversidad.groupby(["location", "date"])

# Calcular media, desviación estándar y número de réplicas
medias = grupos[indices].mean()
desviaciones = grupos[indices].std()
n_replicas = grupos[indices].count()

# Calcular coeficiente de variación (%)
cv = (desviaciones / medias) * 100

# Mostrar resultados
print("MEDIAS:")
display(medias.round(3))

print("DESVIACIONES ESTÁNDAR:")
display(desviaciones.round(3))

print("NÚMERO DE RÉPLICAS:")
display(n_replicas)

print("COEFICIENTES DE VARIACIÓN (%):")
display(cv.round(2))

MEDIAS:

,,Shannon index,Feature_counts,Pielou index,Simpson index,Chao1 index
location,date,,,,,
LC,4_10_2023,5.751,257.000,0.727,0.063,257.000
LL,11_09_2023,5.953,206.333,0.779,0.126,207.333
LRS,4_10_2023,4.892,119.667,0.712,0.244,125.778

DESVIACIONES ESTÁNDAR:

,,Shannon index,Feature_counts,Pielou index,Simpson index,Chao1 index
location,date,,,,,
LC,4_10_2023,0.215,106.240,0.048,0.030,106.240
LL,11_09_2023,0.735,70.890,0.041,0.028,71.933
LRS,4_10_2023,2.115,21.595,0.313,0.231,24.923

NÚMERO DE RÉPLICAS:

,,Shannon index,Feature_counts,Pielou index,Simpson index,Chao1 index
location,date,,,,,
LC,4_10_2023,3,3,3,3,3
LL,11_09_2023,3,3,3,3,3
LRS,4_10_2023,3,3,3,3,3

COEFICIENTES DE VARIACIÓN (%):

,,Shannon index,Feature_counts,Pielou index,Simpson index,Chao1 index
location,date,,,,,
LC,4_10_2023,3.74,41.34,6.65,47.31,41.34
LL,11_09_2023,12.35,34.36,5.27,21.95,34.69
LRS,4_10_2023,43.23,18.05,43.95,94.61,19.81

In [41]:
import pandas as pd

filepath = "/home/tatiana/PROYECTOS/repository/" # change with your path

diversidad = pd.read_csv(
    filepath + "alphadiversity-fungi-table.csv"
)

# Índices de diversidad alfa
indices = [
    "Shannon index",
    "Feature_counts",
    "Pielou index",
    "Simpson index",
    "Chao1 index"
]

# Agrupar las réplicas técnicas por muestra ambiental
grupos = diversidad.groupby(["location", "date"])

# Calcular media, desviación estándar y número de réplicas
medias = grupos[indices].mean()
desviaciones = grupos[indices].std()
replicas = grupos[indices].count()

# Coeficiente de variación (evitando errores de nombres)
cv = (desviaciones / medias) * 100

In [42]:
import pandas as pd
import os

filepath = "/home/tatiana/PROYECTOS/fungil/analysis/"

# Leer datos
diversidad = pd.read_csv(
    os.path.join(filepath, "alphadiversity-fungi-table.csv")
)

# Índices de diversidad alfa
indices = [
    "Shannon index",
    "Feature_counts",
    "Pielou index",
    "Simpson index",
    "Chao1 index"
]

# Agrupar réplicas técnicas por muestra ambiental
grupos = diversidad.groupby(["location", "date"])

# Calcular estadísticos descriptivos
medias = grupos[indices].mean()
desviaciones = grupos[indices].std()
n_replicas = grupos[indices].count()
cv = (desviaciones / medias) * 100

# Construir una única tabla
resultados = pd.concat(
    [
        medias.add_suffix("_mean"),
        desviaciones.add_suffix("_SD"),
        n_replicas.add_suffix("_n"),
        cv.add_suffix("_CV_percent")
    ],
    axis=1
).reset_index()

# Redondear resultados numéricos
columnas_numericas = resultados.select_dtypes(include="number").columns
resultados[columnas_numericas] = resultados[columnas_numericas].round(3)

# Exportar CSV
archivo_salida = os.path.join(
    filepath, "variabilidad_tecnica_alfa_diversidad.csv"
)

resultados.to_csv(
    archivo_salida,
    index=False,
    encoding="utf-8-sig"
)

print("Archivo exportado correctamente:")
print(archivo_salida)

Archivo exportado correctamente:
/home/tatiana/PROYECTOS/fungil/analysis/variabilidad_tecnica_alfa_diversidad.csv

In [43]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Diversity indices
indices = [
    ("Feature_counts", "A) Feature counts"),
    #("Chao1 index", "B) Chao1 index"),
    ("Pielou index", "B) Pielou index"),
    ("Shannon index", "C) Shannon index"),
    ("Simpson index", "D) Simpson index")
]

# Create the figure: one row x four columns
fig = make_subplots(
    rows=1,
    cols=4,
    subplot_titles=[nombre for _, nombre in indices]
)

for col, (indice, nombre) in enumerate(indices, start=1):

    fig.add_trace(
        go.Box(
            x=diversidad["location"],
            y=diversidad[indice],
            name=nombre,
            boxpoints="all",  # Show all the points
            jitter=0.2,
            pointpos=0,
            showlegend=False
        ),
        row=1,
        col=col
    )

fig.update_layout(
    title="Figure 3",
    height=500,
    width=1500,
    template="plotly" # plotly, plotly_white, plotly_dark, seaborn, simple_white, presentation, xgridoff, ygridoof, gridon, none.
)

fig.show()

In [44]:
fig.write_image("fig.fungil_alphadiversity-fron.pdf")